ari:
  application: main
  username: asterisk
  password: YHTEyYRo9SE9cXy6mKEVevJyFk9sFo2M
  http_url: http://192.168.1.2:8088/ari
  websocket_url: ws://192.168.1.2:8088/ari/events

nats:
  url: nats://192.168.1.2:4222
